// Generated from urfave/cli v2.27.7 (the throwaway harness app mirrored in app/tests.rs, each case in a
// fresh process, go1.26.5) by a throwaway program; do not edit.
const GO_CASES: &[GoCase] = &[
    GoCase {
        args: &[],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b""],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"--version"],
        env: &[],
        exit: 0,
        stdout: "dstore version dev\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"-version"],
        env: &[],
        exit: 0,
        stdout: "dstore version dev\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"--version", b"refs"],
        env: &[],
        exit: 0,
        stdout: "dstore version dev\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"-v", b"-h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n    help - Shows a list of commands or help for one command\n\nUSAGE:\n    help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"h", b"h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n    help - Shows a list of commands or help for one command\n\nUSAGE:\n    help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"--help", b"refs"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\nCOMMANDS:\n   init      create a cluster on this store and print its ticket; then run serve\n   status    view, epoch, reachability, disk, transition, gc, voters\n   replicas  change R (a transition that copies 1/R of the store)\n   deep      a nested parent\n   help, h   Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"cluster"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"cluster", b"init"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\nCOMMANDS:\n   init      create a cluster on this store and print its ticket; then run serve\n   status    view, epoch, reachability, disk, transition, gc, voters\n   replicas  change R (a transition that copies 1/R of the store)\n   deep      a nested parent\n   help, h   Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"help", b"init"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster init - create a cluster on this store and print its ticket; then run serve\n\nUSAGE:\n   dstore cluster init [command options]\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --help, -h                                         show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"-h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"watch", b"h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore watch - watch references matching a glob and print each change until interrupted\n\nUSAGE:\n   dstore watch [command options] PATTERN\n\nDESCRIPTION:\n   PATTERN is path-style: * and ? match within one /-separated segment.\n   Every matching reference is printed first.\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--help", b"extra"],
        env: &[],
        exit: 1,
        stdout: "",
        stderr: "dstore: No help topic for 'extra'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"pull", b"--local", b"L", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore store pull - pull the tree under NAME into the local store\n\nUSAGE:\n   dstore store pull [command options] NAME\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value   local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --jobs value    (default: 0)\n   --no-tui        plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"remove", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore node remove\n\nUSAGE:\n   dstore node remove [command options] ID\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --dead          the node is gone: remove its vote first (default: false)\n   --allow-unsafe  (default: false)\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"diff", b"help", b"a.txt"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'a.txt'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"nosuch"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'nosuch'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"nosuch"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'nosuch'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"version"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'version'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"nosuch"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'nosuch'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"help", b"refs"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'refs'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"Refs"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'Refs'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"--log-level"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag needs an argument: -log-level\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: flag needs an argument: -log-level\n",
        probes: &[],
    },
    GoCase {
        args: &[b"-ab"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -ab\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: flag provided but not defined: -ab\n",
        probes: &[],
    },
    GoCase {
        args: &[b"---x"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: bad flag syntax: ---x\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: bad flag syntax: ---x\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"status", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore cluster status - view, epoch, reachability, disk, transition, gc, voters\n\nUSAGE:\n   dstore cluster status [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --store value   store directory [$DSTORE_STORE]\n   --help, -h      show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\nCOMMANDS:\n   init      create a cluster on this store and print its ticket; then run serve\n   status    view, epoch, reachability, disk, transition, gc, voters\n   replicas  change R (a transition that copies 1/R of the store)\n   deep      a nested parent\n   help, h   Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--ticket"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag needs an argument: -ticket\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: flag needs an argument: -ticket\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--log-level", b"debug"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -log-level\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: flag provided but not defined: -log-level\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--no-relay=maybe"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid boolean value \"maybe\" for -no-relay: parse error\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: invalid boolean value \"maybe\" for -no-relay: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--no-relay="],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid boolean value \"\" for -no-relay: parse error\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: invalid boolean value \"\" for -no-relay: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"replicas", b"--yes=maybe", b"3"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid boolean value \"maybe\" for -yes: parse error\n\nNAME:\n   dstore cluster replicas - change R (a transition that copies 1/R of the store)\n\nUSAGE:\n   dstore cluster replicas [command options] R\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --yes           do not ask (default: false)\n   --help, -h      show help\n",
        stderr: "dstore: invalid boolean value \"maybe\" for -yes: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"pull", b"--local", b"L", b"--jobs", b"x", b"n"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"x\" for flag -jobs: parse error\n\nNAME:\n   dstore store pull - pull the tree under NAME into the local store\n\nUSAGE:\n   dstore store pull [command options] NAME\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value   local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --jobs value    (default: 0)\n   --no-tui        plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h      show help\n",
        stderr: "dstore: invalid value \"x\" for flag -jobs: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"pull"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore store pull - pull the tree under NAME into the local store\n\nUSAGE:\n   dstore store pull [command options] NAME\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value   local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --jobs value    (default: 0)\n   --no-tui        plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h      show help\n",
        stderr: "dstore: Required flag \"local\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"pull", b"n"],
        env: &[],
        exit: 1,
        stdout: "",
        stderr: "dstore: Required flag \"local\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"join"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore node join - join a cluster with this store and keep serving\n\nUSAGE:\n   dstore node join [command options]\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --seed value                                       cluster ticket (dstore1…) or comma-separated node ids, found by discovery\n   --token value                                      join token (hex)\n   --no-vote                                          hold no catalog (a relay-only or archive box) (default: false)\n   --help, -h                                         show help\n",
        stderr: "dstore: Required flags \"seed, token\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"join", b"--seed", b"x"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore node join - join a cluster with this store and keep serving\n\nUSAGE:\n   dstore node join [command options]\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --seed value                                       cluster ticket (dstore1…) or comma-separated node ids, found by discovery\n   --token value                                      join token (hex)\n   --no-vote                                          hold no catalog (a relay-only or archive box) (default: false)\n   --help, -h                                         show help\n",
        stderr: "dstore: Required flag \"token\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"join", b"extra"],
        env: &[],
        exit: 1,
        stdout: "",
        stderr: "dstore: Required flags \"seed, token\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"push", b"help"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore store help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore store help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: Required flag \"local\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"join", b"help"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore node help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore node help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: Required flags \"seed, token\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"-h", b"--help"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: Cannot use two forms of the same flag: h help\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: Cannot use two forms of the same flag: h help\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"-h", b"--help"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: Cannot use two forms of the same flag: h help\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: Cannot use two forms of the same flag: h help\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"help", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n    help - Shows a list of commands or help for one command\n\nUSAGE:\n    help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"help", b"x"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'x'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n    help - Shows a list of commands or help for one command\n\nUSAGE:\n    help [command options] [command]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"-h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"h", b"--help", b"cluster"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep - a nested parent\n\nUSAGE:\n   dstore cluster deep [command options]\n\nCOMMANDS:\n   leaf     \n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep - a nested parent\n\nUSAGE:\n   dstore cluster deep [command options]\n\nCOMMANDS:\n   leaf     \n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"cluster", b"deep"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"help", b"deep"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep - a nested parent\n\nUSAGE:\n   dstore cluster deep [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore cluster deep - a nested parent\n\nUSAGE:\n   dstore cluster deep [command options]\n\nCOMMANDS:\n   leaf     \n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"al", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"a", b"-c", b"3", b"-n", b"4"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: Cannot use two forms of the same flag: n c\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: Cannot use two forms of the same flag: n c\n",
        probes: &[],
    },
    GoCase {
        args: &[b"\xc3\xbcn\xc3\xaf", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore ünï - UTF-8 names µ\n\nUSAGE:\n   dstore ünï [command options]\n\nOPTIONS:\n   --µ value                rune widths (default: \"µ\")\n   --ascii-flag-name value  wider in bytes\n   --help, -h               show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"\xc3\xbcn\xc3\xaf"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore ünï - UTF-8 names µ\n\nUSAGE:\n   dstore ünï [command options]\n\nOPTIONS:\n   --µ value                rune widths (default: \"µ\")\n   --ascii-flag-name value  wider in bytes\n   --help, -h               show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"empty", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore empty\n\nUSAGE:\n   dstore empty [command options]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"wrap"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore wrap - first line\n                 second line\n\nUSAGE:\n   dstore wrap [command options] A\nB\n\nDESCRIPTION:\n   para one\n\n      indented\n\nOPTIONS:\n   --multi value  line one\n      line two (default: \"x\\ny\")\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"wrap", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore wrap - first line\n                 second line\n\nUSAGE:\n   dstore wrap [command options] A\nB\n\nDESCRIPTION:\n   para one\n\n      indented\n\nOPTIONS:\n   --multi value  line one\n      line two (default: \"x\\ny\")\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"wrap"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore wrap - first line\n                 second line\n\nUSAGE:\n   dstore wrap [command options] A\nB\n\nDESCRIPTION:\n   para one\n\n      indented\n\nOPTIONS:\n   --multi value  line one\n      line two (default: \"x\\ny\")\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"store", b"push"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore store - push and pull between a standalone local store and the cluster\n\nUSAGE:\n   dstore store [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"help", b"push"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore store push - build a tree from PATH into the local store and push it under NAME\n\nUSAGE:\n   dstore store push [command options] PATH NAME\n\nOPTIONS:\n   --ticket value            cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value             relay URL for the fallback path (default: the built-in relay map)\n   --no-relay                direct addresses only, no relay (default: false)\n   --no-discovery            neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value             local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --user value              user identity recorded in the reference\n   --force                   replace unconditionally (default: false)\n   --expected-version value  CAS: the version ref get printed (hex); omit to require the name to be new\n   --jobs value              (default: 0)\n   --no-tui                  plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h                show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"push", b"--local", b"L", b"help", b"x"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'x'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"join", b"h"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore node help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore node help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: Required flags \"seed, token\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"help", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n    help - Shows a list of commands or help for one command\n\nUSAGE:\n    help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n    help - Shows a list of commands or help for one command\n\nUSAGE:\n    help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"h", b"help", b"cluster"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'cluster'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"--help=false"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"refs"],
        env: &[("DSTORE_NO_DISCOVERY", b"maybe")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"maybe\" as bool value from environment variable \"DSTORE_NO_DISCOVERY\" for flag no-discovery: strconv.ParseBool: parsing \"maybe\": invalid syntax\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: could not parse \"maybe\" as bool value from environment variable \"DSTORE_NO_DISCOVERY\" for flag no-discovery: strconv.ParseBool: parsing \"maybe\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"pull", b"--local", b"L", b"n"],
        env: &[("DSTORE_NO_TUI", b"maybe")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"maybe\" as bool value from environment variable \"DSTORE_NO_TUI\" for flag no-tui: strconv.ParseBool: parsing \"maybe\": invalid syntax\n\nNAME:\n   dstore store pull - pull the tree under NAME into the local store\n\nUSAGE:\n   dstore store pull [command options] NAME\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value   local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --jobs value    (default: 0)\n   --no-tui        plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h      show help\n",
        stderr: "dstore: could not parse \"maybe\" as bool value from environment variable \"DSTORE_NO_TUI\" for flag no-tui: strconv.ParseBool: parsing \"maybe\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"x")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"x\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \"x\": invalid syntax\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"x\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \"x\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"")],
        exit: 1,
        stdout: "NAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: Required flag \"i\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("DUR", b"x")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"x\" as duration value from environment variable \"DUR\" for flag dur: time: invalid duration \"x\"\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"x\" as duration value from environment variable \"DUR\" for flag dur: time: invalid duration \"x\"\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("F64", b"1e400"), ("F64B", b"2")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"1e400\" as float64 value from environment variable \"F64\" for flag f64: strconv.ParseFloat: parsing \"1e400\": value out of range\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"1e400\" as float64 value from environment variable \"F64\" for flag f64: strconv.ParseFloat: parsing \"1e400\": value out of range\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("U", b"-1")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"-1\" as uint value from environment variable \"U\" for flag u: strconv.ParseUint: parsing \"-1\": invalid syntax\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"-1\" as uint value from environment variable \"U\" for flag u: strconv.ParseUint: parsing \"-1\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("I64", b"0x")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"0x\" as int value from environment variable \"I64\" for flag i64: strconv.ParseInt: parsing \"0x\": invalid syntax\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"0x\" as int value from environment variable \"I64\" for flag i64: strconv.ParseInt: parsing \"0x\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs"],
        env: &[
            ("DSTORE_LOG_LEVEL", b"\xff"),
            ("DSTORE_NO_DISCOVERY", b"\xff"),
        ],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"\\xff\" as bool value from environment variable \"DSTORE_NO_DISCOVERY\" for flag no-discovery: strconv.ParseBool: parsing \"\\xff\": invalid syntax\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: could not parse \"\\xff\" as bool value from environment variable \"DSTORE_NO_DISCOVERY\" for flag no-discovery: strconv.ParseBool: parsing \"\\xff\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"1\xff")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"1\\xff\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \"1\\xff\": invalid syntax\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"1\\xff\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \"1\\xff\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"99999999999999999999\xff")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"99999999999999999999\\xff\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \"99999999999999999999\\xff\": value out of range\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"99999999999999999999\\xff\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \"99999999999999999999\\xff\": value out of range\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i=0x10", b"--names", b"a, b", b"-N", b"c"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: Cannot use two forms of the same flag: N names\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: Cannot use two forms of the same flag: N names\n",
        probes: &[],
    },
    GoCase {
        args: &[b"al", b"-=x", b"--advertise-addr", b"--"],
        env: &[("DUR", b"\xff")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"\\xff\" as duration value from environment variable \"DUR\" for flag dur: time: invalid duration \"\\xff\"\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"\\xff\" as duration value from environment variable \"DUR\" for flag dur: time: invalid duration \"\\xff\"\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--", b"--ticket"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=1 args=[\"--ticket\"] first=\"--ticket\"\n  log-level set=false string=\"info\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  ticket set=false string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  no-relay set=false string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  help set=false string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  bogus set=false string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket", "no-relay", "log-level", "help", "bogus"],
    },
    GoCase {
        args: &[b"refs", b"-", b"x"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=2 args=[\"-\" \"x\"] first=\"-\"\n  ticket set=false string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"refs", b"--ticket=a=b", b"p"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=1 args=[\"p\"] first=\"p\"\n  log-level set=false string=\"info\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  ticket set=true string=\"a=b\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket", "log-level"],
    },
    GoCase {
        args: &[b"alias", b"--i", b"1", b"-c", b"3"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  count set=true string=\"3\" bool=false int=3 int64=3 uint=3 float=3 dur=0 slice=[]\n  c set=true string=\"3\" bool=false int=3 int64=3 uint=3 float=3 dur=0 slice=[]\n  n set=true string=\"3\" bool=false int=3 int64=3 uint=3 float=3 dur=0 slice=[]\n  names set=false string=\"[]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  N set=false string=\"[]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  verbose set=false string=\"true\" bool=true int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  V set=false string=\"true\" bool=true int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  dur set=false string=\"1m30s\" bool=false int=0 int64=0 uint=0 float=0 dur=90000000000 slice=[]\n  f64 set=false string=\"1e+21\" bool=false int=0 int64=0 uint=0 float=1e+21 dur=0 slice=[]\n  i64 set=false string=\"0\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  u set=false string=\"0\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  i set=true string=\"1\" bool=true int=1 int64=1 uint=1 float=1 dur=0 slice=[]\n",
        stderr: "",
        probes: &[
            "count", "c", "n", "i", "verbose", "V", "names", "N", "dur", "f64", "i64", "u",
        ],
    },
    GoCase {
        args: &[b"alias", b"-N", b"z"],
        env: &[("I", b"7"), ("NAMES", b" a, ,b ")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  names set=true string=\"[z]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"z\"]\n  N set=true string=\"[z]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"z\"]\n  i set=true string=\"7\" bool=false int=7 int64=7 uint=7 float=7 dur=0 slice=[]\n",
        stderr: "",
        probes: &["names", "N", "i"],
    },
    GoCase {
        args: &[b"alias", b"x"],
        env: &[("I", b"7"), ("NAMES", b" a, ,b ")],
        exit: 0,
        stdout: "action alias narg=1 args=[\"x\"] first=\"x\"\n  names set=true string=\"[a  b]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"a\" \"\" \"b\"]\n  N set=true string=\"[a  b]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"a\" \"\" \"b\"]\n  i set=true string=\"7\" bool=false int=7 int64=7 uint=7 float=7 dur=0 slice=[]\n",
        stderr: "",
        probes: &["names", "N", "i"],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("NAMES", b"")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  names set=true string=\"[]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"\"]\n  N set=true string=\"[]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"\"]\n",
        stderr: "",
        probes: &["names", "N"],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("DUR", b"1h"), ("U", b"0x10")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  dur set=true string=\"1h0m0s\" bool=false int=0 int64=0 uint=0 float=0 dur=3600000000000 slice=[]\n  f64 set=false string=\"1e+21\" bool=false int=0 int64=0 uint=0 float=1e+21 dur=0 slice=[]\n  u set=true string=\"16\" bool=false int=16 int64=16 uint=16 float=16 dur=0 slice=[]\n  i set=true string=\"7\" bool=false int=7 int64=7 uint=7 float=7 dur=0 slice=[]\n",
        stderr: "",
        probes: &["dur", "u", "i", "f64"],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("F64B", b"2")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  f64 set=true string=\"2\" bool=false int=2 int64=2 uint=2 float=2 dur=0 slice=[]\n",
        stderr: "",
        probes: &["f64"],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf"],
        env: &[("RATIO", b"")],
        exit: 0,
        stdout: "action cluster deep leaf narg=0 args=[] first=\"\"\n  log-level set=false string=\"info\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  level set=false string=\"7\" bool=false int=7 int64=7 uint=7 float=7 dur=0 slice=[]\n  ratio set=false string=\"0.25\" bool=false int=0 int64=0 uint=0 float=0.25 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ratio", "level", "log-level"],
    },
    GoCase {
        args: &[b"store", b"pull"],
        env: &[("AMBER_STORE", b"")],
        exit: 0,
        stdout: "action store pull narg=0 args=[] first=\"\"\n  jobs set=false string=\"0\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  local set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  no-tui set=false string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["local", "jobs", "no-tui"],
    },
    GoCase {
        args: &[b"refs"],
        env: &[("DSTORE_TICKET", b"")],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  ticket set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"--log-level", b"x", b"refs"],
        env: &[("DSTORE_LOG_LEVEL", b"debug")],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  log-level set=true string=\"x\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["log-level"],
    },
    GoCase {
        args: &[b"refs", b"fail"],
        env: &[],
        exit: 1,
        stdout: "action refs narg=1 args=[\"fail\"] first=\"fail\"\n  ticket set=false string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "dstore: action failed\n",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"refs", b"exit5"],
        env: &[],
        exit: 5,
        stdout: "action refs narg=1 args=[\"exit5\"] first=\"exit5\"\n  ticket set=false string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "exit five\n",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"refs", b"--help=false", b"x"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=1 args=[\"x\"] first=\"x\"\n  help set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  h set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["help", "h"],
    },
    GoCase {
        args: &[b"--version=false", b"refs"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  help set=false string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  version set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  v set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["version", "v", "help"],
    },
];
