// Generated from urfave/cli v2.27.7 by the review's throwaway harness (the app mirrored in app/tests.rs,
// each case in a fresh process, go1.26.5); do not edit.
const GO_CASES_REVIEW: &[GoCase] = &[
    GoCase {
        args: &[b"refs", b"-h", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore refs help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"-h", b"init"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster init - create a cluster on this store and print its ticket; then run serve\n\nUSAGE:\n   dstore cluster init [command options]\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --help, -h                                         show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"-h", b"deep"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep - a nested parent\n\nUSAGE:\n   dstore cluster deep [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"--help", b"deep", b"leaf"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep - a nested parent\n\nUSAGE:\n   dstore cluster deep [command options]\n\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"-h", b"leaf"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf", b"-h", b"x"],
        env: &[],
        exit: 1,
        stdout: "",
        stderr: "dstore: No help topic for 'x'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"help", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore refs help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"init", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster init - create a cluster on this store and print its ticket; then run serve\n\nUSAGE:\n   dstore cluster init [command options]\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --help, -h                                         show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"help", b"nosuch"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'nosuch'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b""],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b""],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster - init, status, ticket, replicas\n\nUSAGE:\n   dstore cluster [command options]\n\nCOMMANDS:\n   init      create a cluster on this store and print its ticket; then run serve\n   status    view, epoch, reachability, disk, transition, gc, voters\n   replicas  change R (a transition that copies 1/R of the store)\n   deep      a nested parent\n   help, h   Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b""],
        env: &[],
        exit: 0,
        stdout: "action refs narg=1 args=[\"\"] first=\"\"\n  ticket set=false string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"h", b"h", b"h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n    help - Shows a list of commands or help for one command\n\nUSAGE:\n    help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"--", b"refs"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  log-level set=false string=\"info\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["log-level"],
    },
    GoCase {
        args: &[b"wrap", b"x"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'x'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"wrap", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore wrap - first line\n                 second line\n\nUSAGE:\n   dstore wrap [command options] A\nB\n\nDESCRIPTION:\n   para one\n\n      indented\n\nOPTIONS:\n   --multi value  line one\n      line two (default: \"x\\ny\")\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"wrap", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore wrap - first line\n                 second line\n\nUSAGE:\n   dstore wrap [command options] A\nB\n\nDESCRIPTION:\n   para one\n\n      indented\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --multi value  line one\n      line two (default: \"x\\ny\")\n   --help, -h  show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"wrap", b"x"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore wrap - first line\n                 second line\n\nUSAGE:\n   dstore wrap [command options] A\nB\n\nDESCRIPTION:\n   para one\n\n      indented\n\nOPTIONS:\n   --multi value  line one\n      line two (default: \"x\\ny\")\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"help", b"leaf"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"h", b"nosuch"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'nosuch'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"token"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore token - join tokens\n\nUSAGE:\n   dstore token [command options]\n\nCOMMANDS:\n   create   create a single-use join token\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"token", b"h", b"create"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore token create - create a single-use join token\n\nUSAGE:\n   dstore token create [command options]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --weight value  weight the token imposes on the joiner (GiB) (default: 0)\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"join", b"--seed", b"s", b"--token", b"t", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore node join - join a cluster with this store and keep serving\n\nUSAGE:\n   dstore node join [command options]\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --seed value                                       cluster ticket (dstore1…) or comma-separated node ids, found by discovery\n   --token value                                      join token (hex)\n   --no-vote                                          hold no catalog (a relay-only or archive box) (default: false)\n   --help, -h                                         show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"push", b"help", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore store help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore store help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: Required flag \"local\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"push", b"--local", b"L", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore store push - build a tree from PATH into the local store and push it under NAME\n\nUSAGE:\n   dstore store push [command options] PATH NAME\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value            cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value             relay URL for the fallback path (default: the built-in relay map)\n   --no-relay                direct addresses only, no relay (default: false)\n   --no-discovery            neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value             local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --user value              user identity recorded in the reference\n   --force                   replace unconditionally (default: false)\n   --expected-version value  CAS: the version ref get printed (hex); omit to require the name to be new\n   --jobs value              (default: 0)\n   --no-tui                  plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h                show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"help", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore refs help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore refs help [command options] [command]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"refs", b"--bogus"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"status", b"h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore cluster status - view, epoch, reachability, disk, transition, gc, voters\n\nUSAGE:\n   dstore cluster status [command options]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --store value   store directory [$DSTORE_STORE]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"push", b"h"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore store help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore store help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: Required flag \"local\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"h", b"push"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore store push - build a tree from PATH into the local store and push it under NAME\n\nUSAGE:\n   dstore store push [command options] PATH NAME\n\nOPTIONS:\n   --ticket value            cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value             relay URL for the fallback path (default: the built-in relay map)\n   --no-relay                direct addresses only, no relay (default: false)\n   --no-discovery            neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value             local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --user value              user identity recorded in the reference\n   --force                   replace unconditionally (default: false)\n   --expected-version value  CAS: the version ref get printed (hex); omit to require the name to be new\n   --jobs value              (default: 0)\n   --no-tui                  plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h                show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"push", b"-h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore store push - build a tree from PATH into the local store and push it under NAME\n\nUSAGE:\n   dstore store push [command options] PATH NAME\n\nOPTIONS:\n   --ticket value            cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value             relay URL for the fallback path (default: the built-in relay map)\n   --no-relay                direct addresses only, no relay (default: false)\n   --no-discovery            neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --local value             local store directory (layout: <dir>/packstore, <dir>/refs) [$AMBER_STORE]\n   --user value              user identity recorded in the reference\n   --force                   replace unconditionally (default: false)\n   --expected-version value  CAS: the version ref get printed (hex); omit to require the name to be new\n   --jobs value              (default: 0)\n   --no-tui                  plain log lines instead of the progress display (default: false) [$DSTORE_NO_TUI]\n   --help, -h                show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"node", b"join", b"-h", b"--seed"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag needs an argument: -seed\n\nNAME:\n   dstore node join - join a cluster with this store and keep serving\n\nUSAGE:\n   dstore node join [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --seed value                                       cluster ticket (dstore1…) or comma-separated node ids, found by discovery\n   --token value                                      join token (hex)\n   --no-vote                                          hold no catalog (a relay-only or archive box) (default: false)\n   --help, -h                                         show help\n",
        stderr: "dstore: flag needs an argument: -seed\n",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"al"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"h", b"a"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"help"],
        env: &[],
        exit: 1,
        stdout: "NAME:\n   dstore alias help - Shows a list of commands or help for one command\n\nUSAGE:\n   dstore alias help [command options] [command]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "dstore: Required flag \"i\" not set\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"empty", b"help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore empty\n\nUSAGE:\n   dstore empty [command options]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"empty", b"x"],
        env: &[],
        exit: 0,
        stdout: "action empty narg=1 args=[\"x\"] first=\"x\"\n  help set=false string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["help"],
    },
    GoCase {
        args: &[b"empty", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore empty\n\nUSAGE:\n   dstore empty [command options]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"help", b"empty"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore empty\n\nUSAGE:\n   dstore empty [command options]\n\nOPTIONS:\n   --help, -h  show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"v"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'v'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"\xc3\xbcn\xc3\xaf"],
        env: &[],
        exit: 3,
        stdout: "",
        stderr: "No help topic for 'ünï'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"-h", b"-h"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"-help", b"-h"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: Cannot use two forms of the same flag: h help\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: Cannot use two forms of the same flag: h help\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"--help=t", b"x"],
        env: &[],
        exit: 1,
        stdout: "",
        stderr: "dstore: No help topic for 'x'\n",
        probes: &[],
    },
    GoCase {
        args: &[b"--help=t", b"refs"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"-v=1", b"-h=0"],
        env: &[],
        exit: 0,
        stdout: "dstore version dev\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"--version=maybe"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid boolean value \"maybe\" for -version: parse error\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: invalid boolean value \"maybe\" for -version: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"-help=maybe"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid boolean value \"maybe\" for -help: parse error\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: invalid boolean value \"maybe\" for -help: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"-=x"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: bad flag syntax: -=x\n\nNAME:\n   dstore - a distributed amber store: cluster nodes and the client\n\nUSAGE:\n   dstore [global options] command [command options]\n\nVERSION:\n   dev\n\nCOMMANDS:\n   cluster       init, status, ticket, replicas\n   token         join tokens\n   node          join, remove, drain\n   store         push and pull between a standalone local store and the cluster\n   refs          list references\n   watch         watch references matching a glob and print each change until interrupted\n   diff          unified diffs of the working directory against the last synced tree\n   alias, al, a  a command with aliases and every flag kind\n   ünï         UTF-8 names µ\n   empty         \n   wrap          first line\n                 second line\n   help, h       Shows a list of commands or help for one command\n\nGLOBAL OPTIONS:\n   --log-level value  debug|info|warn|error (a global flag: give it before the command) (default: \"info\") [$DSTORE_LOG_LEVEL]\n   --help, -h         show help\n   --version, -v      print the version\n",
        stderr: "dstore: bad flag syntax: -=x\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"---"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: bad flag syntax: ---\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: bad flag syntax: ---\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"-"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=1 args=[\"-\"] first=\"-\"\n  ticket set=false string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"--log-level=", b"refs"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  log-level set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["log-level"],
    },
    GoCase {
        args: &[b"-log-level=a", b"-log-level", b"b", b"refs"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  log-level set=true string=\"b\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["log-level"],
    },
    GoCase {
        args: &[b"refs"],
        env: &[("DSTORE_LOG_LEVEL", b"")],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  log-level set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["log-level"],
    },
    GoCase {
        args: &[b"refs"],
        env: &[("DSTORE_NO_DISCOVERY", b"")],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  no-discovery set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["no-discovery"],
    },
    GoCase {
        args: &[b"refs", b"--no-discovery=false"],
        env: &[("DSTORE_NO_DISCOVERY", b"1")],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  no-discovery set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["no-discovery"],
    },
    GoCase {
        args: &[b"refs"],
        env: &[("DSTORE_NO_DISCOVERY", b"TRUE")],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  no-discovery set=true string=\"true\" bool=true int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["no-discovery"],
    },
    GoCase {
        args: &[b"refs"],
        env: &[("DSTORE_NO_DISCOVERY", b"yes")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"yes\" as bool value from environment variable \"DSTORE_NO_DISCOVERY\" for flag no-discovery: strconv.ParseBool: parsing \"yes\": invalid syntax\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: could not parse \"yes\" as bool value from environment variable \"DSTORE_NO_DISCOVERY\" for flag no-discovery: strconv.ParseBool: parsing \"yes\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"status"],
        env: &[("DSTORE_STORE", b"")],
        exit: 0,
        stdout: "action cluster status narg=0 args=[] first=\"\"\n  store set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["store"],
    },
    GoCase {
        args: &[b"cluster", b"status", b"--store=S", b"--ticket", b"T"],
        env: &[("DSTORE_TICKET", b"E")],
        exit: 0,
        stdout: "action cluster status narg=0 args=[] first=\"\"\n  store set=true string=\"S\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  ticket set=true string=\"T\" bool=true int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["store", "ticket"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"--names", b"a", b"--N", b"b"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: Cannot use two forms of the same flag: N names\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: Cannot use two forms of the same flag: N names\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-V", b"-verbose"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: Cannot use two forms of the same flag: V verbose\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: Cannot use two forms of the same flag: V verbose\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-V=false"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  verbose set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  V set=true string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["verbose", "V"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-n", b"5"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  count set=true string=\"5\" bool=false int=5 int64=5 uint=5 float=5 dur=0 slice=[]\n  c set=true string=\"5\" bool=false int=5 int64=5 uint=5 float=5 dur=0 slice=[]\n  n set=true string=\"5\" bool=false int=5 int64=5 uint=5 float=5 dur=0 slice=[]\n",
        stderr: "",
        probes: &["count", "c", "n"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-c", b"5", b"-c", b"6"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  count set=true string=\"6\" bool=false int=6 int64=6 uint=6 float=6 dur=0 slice=[]\n  c set=true string=\"6\" bool=false int=6 int64=6 uint=6 float=6 dur=0 slice=[]\n  n set=true string=\"6\" bool=false int=6 int64=6 uint=6 float=6 dur=0 slice=[]\n",
        stderr: "",
        probes: &["count", "c", "n"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"--count", b"0x_1f"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  count set=true string=\"31\" bool=false int=31 int64=31 uint=31 float=31 dur=0 slice=[]\n",
        stderr: "",
        probes: &["count"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"0b1_0"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  i set=true string=\"2\" bool=false int=2 int64=2 uint=2 float=2 dur=0 slice=[]\n",
        stderr: "",
        probes: &["i"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-u", b"-1"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"-1\" for flag -u: parse error\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: invalid value \"-1\" for flag -u: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-dur", b"-1.5h"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  dur set=true string=\"-1h30m0s\" bool=false int=0 int64=0 uint=0 float=0 dur=-5400000000000 slice=[]\n",
        stderr: "",
        probes: &["dur"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-f64", b"inf"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  f64 set=true string=\"+Inf\" bool=false int=0 int64=0 uint=0 float=+Inf dur=0 slice=[]\n",
        stderr: "",
        probes: &["f64"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-f64", b"0x1p-2"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  f64 set=true string=\"0.25\" bool=false int=0 int64=0 uint=0 float=0.25 dur=0 slice=[]\n",
        stderr: "",
        probes: &["f64"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-f64", b"1_000", b"-c", b"1_000"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  count set=true string=\"1000\" bool=false int=1000 int64=1000 uint=1000 float=1000 dur=0 slice=[]\n  f64 set=true string=\"1000\" bool=false int=1000 int64=1000 uint=1000 float=1000 dur=0 slice=[]\n",
        stderr: "",
        probes: &["f64", "count"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-f64", b"NaN"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  f64 set=true string=\"NaN\" bool=false int=0 int64=0 uint=0 float=NaN dur=0 slice=[]\n",
        stderr: "",
        probes: &["f64"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-c", b"9223372036854775808"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"9223372036854775808\" for flag -c: value out of range\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: invalid value \"9223372036854775808\" for flag -c: value out of range\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-c", b"-9223372036854775808"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  count set=true string=\"-9223372036854775808\" bool=false int=-9223372036854775808 int64=-9223372036854775808 uint=0 float=-9.223372036854776e+18 dur=0 slice=[]\n",
        stderr: "",
        probes: &["count"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-u", b"18446744073709551616"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"18446744073709551616\" for flag -u: value out of range\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: invalid value \"18446744073709551616\" for flag -u: value out of range\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-u", b"18446744073709551615"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  u set=true string=\"18446744073709551615\" bool=false int=0 int64=0 uint=18446744073709551615 float=1.8446744073709552e+19 dur=0 slice=[]\n",
        stderr: "",
        probes: &["u"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-dur", b"9223372036854775807ns"],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  dur set=true string=\"2562047h47m16.854775807s\" bool=false int=0 int64=0 uint=0 float=0 dur=9223372036854775807 slice=[]\n",
        stderr: "",
        probes: &["dur"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-dur", b"2562047h47m16.854775808s"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"2562047h47m16.854775808s\" for flag -dur: parse error\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: invalid value \"2562047h47m16.854775808s\" for flag -dur: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i=08"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"08\" for flag -i: parse error\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: invalid value \"08\" for flag -i: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-names", b" a , b ", b"-names", b""],
        env: &[],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  names set=true string=\"[a b ]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"a\" \"b\" \"\"]\n",
        stderr: "",
        probes: &["names"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1", b"-N", b"z"],
        env: &[("NAMES", b"x,y")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  names set=true string=\"[z]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"z\"]\n  N set=true string=\"[z]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"z\"]\n",
        stderr: "",
        probes: &["names", "N"],
    },
    GoCase {
        args: &[b"alias", b"-i", b"1"],
        env: &[("NAMES", b"x,y")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  names set=true string=\"[x y]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"x\" \"y\"]\n  N set=true string=\"[x y]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"x\" \"y\"]\n",
        stderr: "",
        probes: &["names", "N"],
    },
    GoCase {
        args: &[b"alias"],
        env: &[
            ("I", b"7"),
            ("U", b""),
            ("DUR", b""),
            ("F64", b""),
            ("F64B", b"2"),
        ],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  dur set=false string=\"1m30s\" bool=false int=0 int64=0 uint=0 float=0 dur=90000000000 slice=[]\n  f64 set=false string=\"1e+21\" bool=false int=0 int64=0 uint=0 float=1e+21 dur=0 slice=[]\n  u set=false string=\"0\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["u", "dur", "f64"],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"0x10")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  i set=true string=\"16\" bool=false int=16 int64=16 uint=16 float=16 dur=0 slice=[]\n",
        stderr: "",
        probes: &["i"],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b" 7")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \" 7\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \" 7\": invalid syntax\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \" 7\" as int value from environment variable \"I\" for flag i: strconv.ParseInt: parsing \" 7\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("I64", b"-9223372036854775809")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"-9223372036854775809\" as int value from environment variable \"I64\" for flag i64: strconv.ParseInt: parsing \"-9223372036854775809\": value out of range\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"-9223372036854775809\" as int value from environment variable \"I64\" for flag i64: strconv.ParseInt: parsing \"-9223372036854775809\": value out of range\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("U", b"-0")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"-0\" as uint value from environment variable \"U\" for flag u: strconv.ParseUint: parsing \"-0\": invalid syntax\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: could not parse \"-0\" as uint value from environment variable \"U\" for flag u: strconv.ParseUint: parsing \"-0\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias"],
        env: &[("I", b"7"), ("DUR", b"1\xc2\xb5s")],
        exit: 0,
        stdout: "action alias narg=0 args=[] first=\"\"\n  dur set=true string=\"1µs\" bool=false int=0 int64=0 uint=0 float=0 dur=1000 slice=[]\n",
        stderr: "",
        probes: &["dur"],
    },
    GoCase {
        args: &[
            b"\xc3\xbcn\xc3\xaf",
            b"-\xc2\xb5",
            b"x",
            b"--ascii-flag-name",
            b"y",
        ],
        env: &[],
        exit: 0,
        stdout: "action ünï narg=0 args=[] first=\"\"\n  µ set=true string=\"x\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  ascii-flag-name set=true string=\"y\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["µ", "ascii-flag-name"],
    },
    GoCase {
        args: &[b"\xc3\xbcn\xc3\xaf", b"--\xc2\xb5="],
        env: &[],
        exit: 0,
        stdout: "action ünï narg=0 args=[] first=\"\"\n  µ set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["µ"],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf"],
        env: &[("RATIO", b"0x1p-1")],
        exit: 0,
        stdout: "action cluster deep leaf narg=0 args=[] first=\"\"\n  ratio set=true string=\"0.5\" bool=false int=0 int64=0 uint=0 float=0.5 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ratio"],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf"],
        env: &[("RATIO", b"abc")],
        exit: 1,
        stdout: "Incorrect Usage: could not parse \"abc\" as float64 value from environment variable \"RATIO\" for flag ratio: strconv.ParseFloat: parsing \"abc\": invalid syntax\n\nNAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "dstore: could not parse \"abc\" as float64 value from environment variable \"RATIO\" for flag ratio: strconv.ParseFloat: parsing \"abc\": invalid syntax\n",
        probes: &[],
    },
    GoCase {
        args: &[
            b"cluster", b"deep", b"leaf", b"-level", b"0x10", b"-ratio", b"1e3", b"a", b"b",
        ],
        env: &[],
        exit: 0,
        stdout: "action cluster deep leaf narg=2 args=[\"a\" \"b\"] first=\"a\"\n  level set=true string=\"16\" bool=false int=16 int64=16 uint=16 float=16 dur=0 slice=[]\n  ratio set=true string=\"1000\" bool=false int=1000 int64=1000 uint=1000 float=1000 dur=0 slice=[]\n",
        stderr: "",
        probes: &["level", "ratio"],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf", b"-level=-1"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"-1\" for flag -level: parse error\n\nNAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "dstore: invalid value \"-1\" for flag -level: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf", b"-ratio=0x"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"0x\" for flag -ratio: parse error\n\nNAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "dstore: invalid value \"0x\" for flag -ratio: parse error\n",
        probes: &[],
    },
    GoCase {
        args: &[b"cluster", b"deep", b"leaf", b"-ratio", b"1e400"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"1e400\" for flag -ratio: value out of range\n\nNAME:\n   dstore cluster deep leaf\n\nUSAGE:\n   dstore cluster deep leaf [command options] X\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --level value  depth (default: 7)\n   --ratio value  dead ratio (default: 0.25) [$RATIO]\n   --help, -h     show help\n",
        stderr: "dstore: invalid value \"1e400\" for flag -ratio: value out of range\n",
        probes: &[],
    },
    GoCase {
        args: &[
            b"node",
            b"join",
            b"--seed",
            b"x",
            b"--token",
            b"y",
            b"--advertise-addr",
            b"a, b",
            b"--advertise-addr",
            b"c",
        ],
        env: &[],
        exit: 0,
        stdout: "action node join narg=0 args=[] first=\"\"\n  advertise-addr set=true string=\"[a b c]\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[\"a\" \"b\" \"c\"]\n  seed set=true string=\"x\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  token set=true string=\"y\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["advertise-addr", "seed", "token"],
    },
    GoCase {
        args: &[
            b"node",
            b"join",
            b"--seed",
            b"x",
            b"--token",
            b"y",
            b"--gc-interval",
            b"90m",
            b"--rate",
            b"-5",
            b"--replicas",
            b"010",
        ],
        env: &[],
        exit: 0,
        stdout: "action node join narg=0 args=[] first=\"\"\n  rate set=true string=\"-5\" bool=false int=-5 int64=-5 uint=0 float=-5 dur=0 slice=[]\n  gc-interval set=true string=\"1h30m0s\" bool=false int=0 int64=0 uint=0 float=0 dur=5400000000000 slice=[]\n  replicas set=true string=\"8\" bool=false int=8 int64=8 uint=8 float=8 dur=0 slice=[]\n",
        stderr: "",
        probes: &["gc-interval", "rate", "replicas"],
    },
    GoCase {
        args: &[b"node", b"join", b"--seed=x", b"--token="],
        env: &[],
        exit: 0,
        stdout: "action node join narg=0 args=[] first=\"\"\n  token set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["token"],
    },
    GoCase {
        args: &[
            b"node",
            b"join",
            b"--seed",
            b"x",
            b"--token",
            b"y",
            b"--jobs",
            b"0x8000000000000000",
        ],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: invalid value \"0x8000000000000000\" for flag -jobs: value out of range\n\nNAME:\n   dstore node join - join a cluster with this store and keep serving\n\nUSAGE:\n   dstore node join [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --store value                                      store directory [$DSTORE_STORE]\n   --paxos-dir value                                  acceptor state directory (default <store>/paxos; put it on its own device)\n   --rate value                                       reconcile copy rate in bytes/s (0 = unlimited) (default: 0)\n   --jobs value                                       parallelism (0 = cores) (default: 0)\n   --pack-size value                                  size at which the active pack is sealed (bytes or Ki/Mi/Gi/Ti); applies to packs written from now on (default: \"2Gi\") [$DSTORE_PACK_SIZE]\n   --gateway                                          also serve the transport-iroh ALPN (not implemented in this version) (default: false)\n   --gc-interval value                                (default: 4h0m0s)\n   --put-ttl value                                    (default: 1h0m0s)\n   --advertise-addr value [ --advertise-addr value ]  direct address to advertise, ip or ip:port (repeatable)\n   --no-discovery                                     neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --replicas value                                   R: owners per object (default: 3)\n   --weight value                                     capacity in GiB, or auto (default: \"auto\")\n   --zone value                                       \n   --allow-unsafe                                     allow min-replicas 1 (default: false)\n   --seed value                                       cluster ticket (dstore1…) or comma-separated node ids, found by discovery\n   --token value                                      join token (hex)\n   --no-vote                                          hold no catalog (a relay-only or archive box) (default: false)\n   --help, -h                                         show help\n",
        stderr: "dstore: invalid value \"0x8000000000000000\" for flag -jobs: value out of range\n",
        probes: &[],
    },
    GoCase {
        args: &[b"store", b"pull", b"--local=", b"n"],
        env: &[],
        exit: 0,
        stdout: "action store pull narg=1 args=[\"n\"] first=\"n\"\n  local set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["local"],
    },
    GoCase {
        args: &[b"refs", b"-ticket"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag needs an argument: -ticket\n\nNAME:\n   dstore refs - list references\n\nUSAGE:\n   dstore refs [command options] [PREFIX]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: flag needs an argument: -ticket\n",
        probes: &[],
    },
    GoCase {
        args: &[b"refs", b"-ticket", b"-no-relay"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  ticket set=true string=\"-no-relay\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  no-relay set=false string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket", "no-relay"],
    },
    GoCase {
        args: &[b"refs", b"--ticket=x=y=z"],
        env: &[],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  ticket set=true string=\"x=y=z\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"refs", b"-ticket="],
        env: &[],
        exit: 0,
        stdout: "action refs narg=0 args=[] first=\"\"\n  ticket set=true string=\"\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["ticket"],
    },
    GoCase {
        args: &[b"diff", b"a.txt", b"--stat"],
        env: &[],
        exit: 0,
        stdout: "action diff narg=2 args=[\"a.txt\" \"--stat\"] first=\"a.txt\"\n  stat set=false string=\"false\" bool=false int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["stat"],
    },
    GoCase {
        args: &[b"diff", b"-stat=1", b"-remote=T", b"x"],
        env: &[],
        exit: 0,
        stdout: "action diff narg=1 args=[\"x\"] first=\"x\"\n  remote set=true string=\"true\" bool=true int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n  stat set=true string=\"true\" bool=true int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["stat", "remote"],
    },
    GoCase {
        args: &[b"cluster", b"replicas", b"--yes", b"3", b"extra"],
        env: &[],
        exit: 0,
        stdout: "action cluster replicas narg=2 args=[\"3\" \"extra\"] first=\"3\"\n  yes set=true string=\"true\" bool=true int=0 int64=0 uint=0 float=0 dur=0 slice=[]\n",
        stderr: "",
        probes: &["yes"],
    },
    GoCase {
        args: &[b"watch", b"--help"],
        env: &[],
        exit: 0,
        stdout: "NAME:\n   dstore watch - watch references matching a glob and print each change until interrupted\n\nUSAGE:\n   dstore watch [command options] PATTERN\n\nDESCRIPTION:\n   PATTERN is path-style: * and ? match within one /-separated segment.\n   Every matching reference is printed first.\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "",
        probes: &[],
    },
    GoCase {
        args: &[b"watch", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore watch - watch references matching a glob and print each change until interrupted\n\nUSAGE:\n   dstore watch [command options] PATTERN\n\nDESCRIPTION:\n   PATTERN is path-style: * and ? match within one /-separated segment.\n   Every matching reference is printed first.\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --ticket value  cluster ticket (dstore1…) or comma-separated node ids, found by discovery [$DSTORE_TICKET]\n   --relay value   relay URL for the fallback path (default: the built-in relay map)\n   --no-relay      direct addresses only, no relay (default: false)\n   --no-discovery  neither announce this endpoint nor resolve node ids by discovery (mDNS and, with relays, number0's DNS) (default: false) [$DSTORE_NO_DISCOVERY]\n   --help, -h      show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"\xc3\xbcn\xc3\xaf", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore ünï - UTF-8 names µ\n\nUSAGE:\n   dstore ünï [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --µ value                rune widths (default: \"µ\")\n   --ascii-flag-name value  wider in bytes\n   --help, -h               show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
    GoCase {
        args: &[b"alias", b"--bogus"],
        env: &[],
        exit: 1,
        stdout: "Incorrect Usage: flag provided but not defined: -bogus\n\nNAME:\n   dstore alias - a command with aliases and every flag kind\n\nUSAGE:\n   dstore alias [command options]\n\nCOMMANDS:\n   help, h  Shows a list of commands or help for one command\n\nOPTIONS:\n   --count N, -c N, -n N                                how many N to take (default: -2)\n   --names value, -N value [ --names value, -N value ]  names, comma-separated [$NAMES]\n   --verbose, -V                                        (default: true)\n   --dur value                                          a duration (default: 1m30s) [$DUR]\n   --f64 value                                          (default: 1e+21) [$F64, $F64B]\n   --i64 value                                          (default: 0) [$I64]\n   -u value                                             (default: 0) [$U]\n   -i value                                             (default: 0) [$I]\n   --help, -h                                           show help\n",
        stderr: "dstore: flag provided but not defined: -bogus\n",
        probes: &[],
    },
];
