//! Field types of keyasint structs and the `Struct` trait `cbor_struct!` implements.

use crate::{Dec, DecodeError, Enc, Encode};

/// Implemented for the field types dstore uses: bool, u8, u16, u32, u64, i64, f64, String, Vec<u8>,
/// Option<Vec<u8>>, Vec<Vec<u8>>, Vec<Option<Vec<u8>>>, Vec<String>, Vec<u16>, Vec<T: Struct>,
/// Option<Vec<T: Struct>>, Option<Box<T: Struct>>. Vec<Vec<u8>> decodes a null element as an empty
/// vector (codec-wire-ticket R6); Vec<Option<Vec<u8>>> keeps it as None (views, which golden tests
/// re-encode).
pub trait Field: Sized + Default {
    fn encode_field(&self, e: &mut Enc);
    /// fxamacker omitempty emptiness.
    fn is_empty_field(&self) -> bool;
    /// The element Go type is `go_type` without a leading "[]".
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError>;
}

/// A keyasint CBOR struct (generated by `cbor_struct!`).
pub trait Struct: Encode + Sized + Default {
    /// "wire.Msg".
    const GO_NAME: &'static str;
    fn decode_struct(d: &mut Dec<'_>) -> Result<Self, DecodeError>;
}

impl Field for bool {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for u8 {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for u16 {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for u32 {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for u64 {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for i64 {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for f64 {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for String {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for Vec<u8> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for Option<Vec<u8>> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for Vec<Vec<u8>> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for Vec<Option<Vec<u8>>> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for Vec<String> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl Field for Vec<u16> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl<T: Struct> Field for Vec<T> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl<T: Struct> Field for Option<Vec<T>> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}

impl<T: Struct> Field for Option<Box<T>> {
    fn encode_field(&self, e: &mut Enc) {
        todo!()
    }
    fn is_empty_field(&self) -> bool {
        todo!()
    }
    fn decode_field(d: &mut Dec<'_>, go_type: &'static str) -> Result<Self, DecodeError> {
        todo!()
    }
}
