// Command goerrno prints crates/gocompat/src/errno_tables.rs: Go's syscall
// errno text tables (the `errors` array of syscall/zerrors_<os>_<arch>.go) for
// darwin and linux on amd64 and arm64, as Rust statics selected by cfg. Usage:
//
//	go run ./cmd/goerrno > ../../crates/gocompat/src/errno_tables.rs
//
// The tables are read from the running toolchain's GOROOT with go/parser, so
// one host generates every target. When the host is one of the four targets,
// the parsed table is also checked against syscall.Errno.Error().
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"syscall"
)

// wantGo is the toolchain whose tables the port reproduces (PORTING.md §0).
const wantGo = "go1.26.5"

type target struct {
	goos, goarch string
	cfg          string
}

// targets are emitted in this order. The fallback cfgs keep the crate
// compiling on other architectures of the same OS.
var targets = []target{
	{"darwin", "arm64", `all(target_os = "macos", not(target_arch = "x86_64"))`},
	{"darwin", "amd64", `all(target_os = "macos", target_arch = "x86_64")`},
	{"linux", "amd64", `all(target_os = "linux", not(target_arch = "aarch64"))`},
	{"linux", "arm64", `all(target_os = "linux", target_arch = "aarch64")`},
}

type entry struct {
	code int
	text string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "goerrno:", err)
		os.Exit(1)
	}
}

func run() error {
	if runtime.Version() != wantGo {
		return fmt.Errorf("toolchain is %s, want %s (GOTOOLCHAIN=local in the flake dev shell)", runtime.Version(), wantGo)
	}
	goroot, err := goRoot()
	if err != nil {
		return err
	}
	var out bytes.Buffer
	out.WriteString(`//! Go ` + "`syscall`" + ` errno tables (` + "`zerrors_darwin_*.go`, `zerrors_linux_*.go`" + ` of ` + wantGo + `), one per
//! ` + "`cfg(target_os, target_arch)`" + `, used by ` + "`errno::errno_text`" + `.
//!
//! Generated by ` + "`go run ./cmd/goerrno`" + ` in tools/vectorgen; do not edit by hand. The amd64 and arm64
//! tables differ: darwin/arm64 adds 106 (EQFULL) and linux/arm64 adds 133 (EHWPOISON).
`)
	for _, t := range targets {
		entries, err := parseTable(filepath.Join(goroot, "src", "syscall", "zerrors_"+t.goos+"_"+t.goarch+".go"))
		if err != nil {
			return err
		}
		if t.goos == runtime.GOOS && t.goarch == runtime.GOARCH {
			if err := checkHost(entries); err != nil {
				return err
			}
		}
		fmt.Fprintf(&out, "\n/// `(errno, Go text)` pairs of `syscall/zerrors_%s_%s.go`, ascending.\n", t.goos, t.goarch)
		fmt.Fprintf(&out, "#[cfg(%s)]\n", t.cfg)
		out.WriteString("pub(crate) static ERRORS: &[(i32, &str)] = &[\n")
		for _, e := range entries {
			fmt.Fprintf(&out, "    (%d, %s),\n", e.code, rustString(e.text))
		}
		out.WriteString("];\n")
	}
	out.WriteString("\n/// No Go table for this target (dstore is Unix-only: macOS and Linux).\n")
	out.WriteString(`#[cfg(not(any(target_os = "macos", target_os = "linux")))]` + "\n")
	out.WriteString("pub(crate) static ERRORS: &[(i32, &str)] = &[];\n")
	_, err = os.Stdout.Write(out.Bytes())
	return err
}

// goRoot asks the go command for GOROOT, falling back to the runtime's.
func goRoot() (string, error) {
	b, err := exec.Command("go", "env", "GOROOT").Output()
	if err == nil {
		if s := strings.TrimSpace(string(b)); s != "" {
			return s, nil
		}
	}
	if s := runtime.GOROOT(); s != "" {
		return s, nil
	}
	return "", fmt.Errorf("cannot determine GOROOT: %v", err)
}

// parseTable extracts `var errors = [...]string{N: "text", ...}` from a
// zerrors file.
func parseTable(path string) ([]entry, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, err
	}
	var entries []entry
	found := false
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.VAR {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) != 1 || vs.Names[0].Name != "errors" || len(vs.Values) != 1 {
				continue
			}
			lit, ok := vs.Values[0].(*ast.CompositeLit)
			if !ok {
				return nil, fmt.Errorf("%s: errors is not a composite literal", path)
			}
			found = true
			for _, elt := range lit.Elts {
				kv, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					return nil, fmt.Errorf("%s: errors element without a key", path)
				}
				k, ok := kv.Key.(*ast.BasicLit)
				v, ok2 := kv.Value.(*ast.BasicLit)
				if !ok || !ok2 || k.Kind != token.INT || v.Kind != token.STRING {
					return nil, fmt.Errorf("%s: unexpected errors element", path)
				}
				code, err := strconv.Atoi(k.Value)
				if err != nil {
					return nil, err
				}
				text, err := strconv.Unquote(v.Value)
				if err != nil {
					return nil, err
				}
				entries = append(entries, entry{code, text})
			}
		}
	}
	if !found {
		return nil, fmt.Errorf("%s: no errors table", path)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].code < entries[j].code })
	for i := 1; i < len(entries); i++ {
		if entries[i].code == entries[i-1].code {
			return nil, fmt.Errorf("%s: errno %d listed twice", path, entries[i].code)
		}
	}
	return entries, nil
}

// checkHost compares a parsed table with the running syscall package.
func checkHost(entries []entry) error {
	byCode := map[int]string{}
	maxCode := 0
	for _, e := range entries {
		byCode[e.code] = e.text
		maxCode = max(maxCode, e.code)
	}
	for code := 0; code <= maxCode+1; code++ {
		want := "errno " + strconv.Itoa(code)
		if s := byCode[code]; s != "" {
			want = s
		}
		if got := syscall.Errno(code).Error(); got != want {
			return fmt.Errorf("host table mismatch at errno %d: parsed %q, syscall says %q", code, want, got)
		}
	}
	return nil
}

// rustString renders s as a Rust string literal.
func rustString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r < 0x20 || r >= 0x7f:
			fmt.Fprintf(&b, `\u{%x}`, r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
