//! Unicode and `strconv` tables of go1.26.5: the `strconv` isPrint/isNotPrint/isGraphic tables,
//! `unicode.White_Space`, and every rune whose `unicode.ToLower`/`ToUpper` differs from itself.
//!
//! GENERATED by `tools/vectorgen/cmd/gotables`; do not edit. CI regenerates this file and diffs it.
//!
//! L0 placeholder: the gocompat owner replaces this file with the generator's output.
