//! Golden tests of `dstore-gocompat` `strconv` and `time` against `gocompat/numtime.json`, generated by
//! `tools/vectorgen/family_gocompat_numtime.go` from go1.26.5 (schema: `tools/vectorgen/docs/gocompat-b.md`).

use std::sync::OnceLock;

use dstore_gocompat::strconv::{self, NumError, NumErrorKind};
use dstore_gocompat::time::{self as gotime, FixedZone, GoTime};
use dstore_testkit::golden::{decimal_i64, decimal_u64, load_json};
use serde::Deserialize;

#[derive(Deserialize)]
struct BoolCase {
    #[serde(rename = "in")]
    input: String,
    value: bool,
    err: String,
}

#[derive(Deserialize)]
struct IntCase {
    #[serde(rename = "in")]
    input: String,
    base: u32,
    bit_size: u32,
    #[serde(deserialize_with = "decimal_i64")]
    value: i64,
    err: String,
}

#[derive(Deserialize)]
struct UintCase {
    #[serde(rename = "in")]
    input: String,
    base: u32,
    bit_size: u32,
    #[serde(deserialize_with = "decimal_u64")]
    value: u64,
    err: String,
}

#[derive(Deserialize)]
struct FloatCase {
    #[serde(rename = "in")]
    input: String,
    #[serde(deserialize_with = "decimal_u64")]
    bits: u64,
    err: String,
}

#[derive(Deserialize)]
struct FormatFloatCase {
    #[serde(deserialize_with = "decimal_u64")]
    bits: u64,
    out: String,
}

#[derive(Deserialize)]
struct DurStringCase {
    #[serde(deserialize_with = "decimal_i64")]
    ns: i64,
    out: String,
}

#[derive(Deserialize)]
struct DurRoundCase {
    #[serde(deserialize_with = "decimal_i64")]
    ns: i64,
    #[serde(deserialize_with = "decimal_i64")]
    m: i64,
    #[serde(deserialize_with = "decimal_i64")]
    out: i64,
}

#[derive(Deserialize)]
struct ParseDurCase {
    #[serde(rename = "in")]
    input: String,
    #[serde(deserialize_with = "decimal_i64")]
    ns: i64,
    err: String,
}

#[derive(Deserialize)]
struct ZonedCase {
    #[serde(deserialize_with = "decimal_i64")]
    unix_secs: i64,
    nanos: u32,
    offset_secs: i32,
    out: String,
}

#[derive(Deserialize)]
struct UtcCase {
    #[serde(deserialize_with = "decimal_i64")]
    unix_secs: i64,
    nanos: u32,
    out: String,
}

#[derive(Deserialize)]
struct ParseTimeCase {
    #[serde(rename = "in")]
    input: String,
    #[serde(deserialize_with = "decimal_i64")]
    unix_secs: i64,
    nanos: u32,
    err: String,
}

#[derive(Deserialize)]
struct NumtimeFile {
    parse_bool: Vec<BoolCase>,
    parse_int: Vec<IntCase>,
    parse_uint: Vec<UintCase>,
    parse_float: Vec<FloatCase>,
    format_float_g: Vec<FormatFloatCase>,
    duration_string: Vec<DurStringCase>,
    duration_round: Vec<DurRoundCase>,
    parse_duration: Vec<ParseDurCase>,
    rfc3339_local: Vec<ZonedCase>,
    rfc3339nano_utc: Vec<UtcCase>,
    slog_time: Vec<ZonedCase>,
    clock: Vec<ZonedCase>,
    log_std: Vec<ZonedCase>,
    parse_rfc3339nano: Vec<ParseTimeCase>,
}

fn vectors() -> &'static NumtimeFile {
    static FILE: OnceLock<NumtimeFile> = OnceLock::new();
    FILE.get_or_init(|| load_json("gocompat/numtime.json"))
}

/// Collects mismatches, then fails listing the first ones.
struct Mismatches {
    name: &'static str,
    total: usize,
    lines: Vec<String>,
}

impl Mismatches {
    fn new(name: &'static str) -> Mismatches {
        Mismatches {
            name,
            total: 0,
            lines: Vec::new(),
        }
    }

    fn check(&mut self, ok: bool, msg: impl FnOnce() -> String) {
        self.total += 1;
        if !ok {
            self.lines.push(msg());
        }
    }

    fn finish(self) {
        assert!(self.total > 0, "{}: no vectors", self.name);
        assert!(
            self.lines.is_empty(),
            "{}: {} of {} cases differ from Go:\n{}",
            self.name,
            self.lines.len(),
            self.total,
            self.lines[..self.lines.len().min(25)].join("\n")
        );
    }
}

/// The class named by a Go `NumError` text.
fn kind_of(err: &str) -> Option<NumErrorKind> {
    if err.ends_with(": invalid syntax") {
        Some(NumErrorKind::Syntax)
    } else if err.ends_with(": value out of range") {
        Some(NumErrorKind::Range)
    } else {
        None
    }
}

/// The fields of a `NumError` against Go's text (func, input, class), without rendering it.
fn num_error_matches(e: &NumError, func: &str, input: &str, err: &str) -> bool {
    !err.is_empty()
        && e.func == func
        && e.num == input
        && kind_of(err) == Some(e.kind)
        && err.starts_with(&format!("strconv.{func}: parsing "))
}

#[test]
fn parse_bool_values() {
    let mut m = Mismatches::new("parse_bool");
    for c in &vectors().parse_bool {
        let got = strconv::parse_bool(&c.input);
        let ok = match &got {
            Ok(v) => c.err.is_empty() && *v == c.value,
            Err(e) => num_error_matches(e, "ParseBool", &c.input, &c.err),
        };
        m.check(ok, || {
            format!("{:?}: got {got:?}, want {:?} {:?}", c.input, c.value, c.err)
        });
    }
    m.finish();
}

#[test]
fn parse_int_values() {
    let mut m = Mismatches::new("parse_int");
    for c in &vectors().parse_int {
        let got = strconv::parse_int(&c.input, c.base, c.bit_size);
        let ok = match &got {
            Ok(v) => c.err.is_empty() && *v == c.value,
            Err(e) => num_error_matches(e, "ParseInt", &c.input, &c.err),
        };
        m.check(ok, || {
            format!(
                "{:?} base {} bits {}: got {got:?}, want {} {:?}",
                c.input, c.base, c.bit_size, c.value, c.err
            )
        });
    }
    m.finish();
}

#[test]
fn parse_uint_values() {
    let mut m = Mismatches::new("parse_uint");
    for c in &vectors().parse_uint {
        let got = strconv::parse_uint(&c.input, c.base, c.bit_size);
        let ok = match &got {
            Ok(v) => c.err.is_empty() && *v == c.value,
            Err(e) => num_error_matches(e, "ParseUint", &c.input, &c.err),
        };
        m.check(ok, || {
            format!(
                "{:?} base {} bits {}: got {got:?}, want {} {:?}",
                c.input, c.base, c.bit_size, c.value, c.err
            )
        });
    }
    m.finish();
}

#[test]
fn parse_float_values() {
    let mut m = Mismatches::new("parse_float");
    for c in &vectors().parse_float {
        let got = strconv::parse_float(&c.input);
        let ok = match &got {
            Ok(f) => c.err.is_empty() && f.to_bits() == c.bits,
            Err(e) => num_error_matches(e, "ParseFloat", &c.input, &c.err),
        };
        m.check(ok, || {
            let shown: String = c.input.chars().take(80).collect();
            format!(
                "{shown:?}: got {:?}, want bits {:#018x} {:?}",
                got.map(f64::to_bits),
                c.bits,
                c.err
            )
        });
    }
    m.finish();
}

/// Renders every `NumError` (needs `dstore_gocompat::quote`).
#[test]
fn parse_number_error_texts() {
    let v = vectors();
    let mut m = Mismatches::new("strconv error texts");
    let mut check = |got: Option<String>, want: &str| {
        m.check(got.as_deref().unwrap_or("") == want, || {
            format!("got {got:?}, want {want:?}")
        });
    };
    for c in &v.parse_bool {
        check(
            strconv::parse_bool(&c.input).err().map(|e| e.to_string()),
            &c.err,
        );
    }
    for c in &v.parse_int {
        check(
            strconv::parse_int(&c.input, c.base, c.bit_size)
                .err()
                .map(|e| e.to_string()),
            &c.err,
        );
    }
    for c in &v.parse_uint {
        check(
            strconv::parse_uint(&c.input, c.base, c.bit_size)
                .err()
                .map(|e| e.to_string()),
            &c.err,
        );
    }
    for c in &v.parse_float {
        check(
            strconv::parse_float(&c.input).err().map(|e| e.to_string()),
            &c.err,
        );
    }
    m.finish();
}

#[test]
fn format_float_g() {
    let mut m = Mismatches::new("format_float_g");
    for c in &vectors().format_float_g {
        let got = strconv::format_float_g(f64::from_bits(c.bits));
        m.check(got == c.out, || {
            format!("bits {:#018x}: got {got:?}, want {:?}", c.bits, c.out)
        });
    }
    m.finish();
}

#[test]
fn duration_string() {
    let mut m = Mismatches::new("duration_string");
    for c in &vectors().duration_string {
        let got = gotime::duration_string(c.ns);
        m.check(got == c.out, || {
            format!("{}: got {got:?}, want {:?}", c.ns, c.out)
        });
    }
    m.finish();
}

#[test]
fn duration_round() {
    let mut m = Mismatches::new("duration_round");
    for c in &vectors().duration_round {
        let got = gotime::duration_round(c.ns, c.m);
        m.check(got == c.out, || {
            format!("{} round {}: got {got}, want {}", c.ns, c.m, c.out)
        });
    }
    m.finish();
}

#[test]
fn parse_duration() {
    let mut m = Mismatches::new("parse_duration");
    for c in &vectors().parse_duration {
        let got = gotime::parse_duration(&c.input);
        let ok = match &got {
            Ok(ns) => c.err.is_empty() && *ns == c.ns,
            Err(e) => *e == c.err,
        };
        m.check(ok, || {
            format!("{:?}: got {got:?}, want {} {:?}", c.input, c.ns, c.err)
        });
    }
    m.finish();
}

fn zoned(name: &'static str, cases: &[ZonedCase], f: impl Fn(GoTime, &FixedZone) -> String) {
    let mut m = Mismatches::new(name);
    for c in cases {
        let t = GoTime {
            unix_secs: c.unix_secs,
            nanos: c.nanos,
        };
        let got = f(t, &FixedZone(c.offset_secs));
        m.check(got == c.out, || {
            format!(
                "{}.{:09} at {:+}s: got {got:?}, want {:?}",
                c.unix_secs, c.nanos, c.offset_secs, c.out
            )
        });
    }
    m.finish();
}

#[test]
fn rfc3339_local() {
    zoned("rfc3339_local", &vectors().rfc3339_local, |t, z| {
        gotime::format_rfc3339(t, z)
    });
}

#[test]
fn slog_time() {
    zoned("slog_time", &vectors().slog_time, |t, z| {
        gotime::format_slog_time(t, z)
    });
}

#[test]
fn clock() {
    zoned("clock", &vectors().clock, |t, z| gotime::format_clock(t, z));
}

#[test]
fn log_std() {
    zoned("log_std", &vectors().log_std, |t, z| {
        gotime::format_log_std(t, z)
    });
}

#[test]
fn rfc3339nano_utc() {
    let mut m = Mismatches::new("rfc3339nano_utc");
    for c in &vectors().rfc3339nano_utc {
        let got = gotime::format_rfc3339nano_utc(GoTime {
            unix_secs: c.unix_secs,
            nanos: c.nanos,
        });
        m.check(got == c.out, || {
            format!(
                "{}.{:09}: got {got:?}, want {:?}",
                c.unix_secs, c.nanos, c.out
            )
        });
    }
    m.finish();
}

#[test]
fn parse_rfc3339nano() {
    let mut m = Mismatches::new("parse_rfc3339nano");
    for c in &vectors().parse_rfc3339nano {
        let got = gotime::parse_rfc3339nano(&c.input);
        let ok = match &got {
            Ok(t) => {
                c.err.is_empty()
                    && *t
                        == GoTime {
                            unix_secs: c.unix_secs,
                            nanos: c.nanos,
                        }
            }
            Err(e) => *e == c.err,
        };
        m.check(ok, || {
            format!(
                "{:?}: got {got:?}, want {}.{:09} {:?}",
                c.input, c.unix_secs, c.nanos, c.err
            )
        });
    }
    m.finish();
}
